server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_product?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:

  cloud:
    alibaba:
      seata:
        tx-service-group: seata-product
  application:
    name: seata-product
# 下载seata release 包并进行启动
# https://github.com/seata/seata/releases/download/v1.4.2/seata-server-1.4.2.zip
seata:
  service:
    vgroup-mapping:
      seata-product: default
#      default与grouplist的default对应
    grouplist:
      default: 127.0.0.1:8091